### ISSUE TITLE
Project To Do List

### ISSUE THREAD

**Issue by MattMakesNoise** [MattMakesNoise/Netmatters-HTML-CSS-JS-Reflection#1]
**TODO**

- [x] Get plan together....layout, images/icons/buttons needed, colors
- [x] Get Sass and Bootstrap up and running
- [x] Difference between mobile, tablet and desktop versions (breakpoints)
- [x] Get images and icons needed.
- [x] Set up Sass variables
- [x] Get base mobile layout done.
- [x] Fill header
- [x] Do hero
- [x] Do Cards
- [x] Do About
- [x] News
- [x] Email signup
- [x] Footer
- [x] Set breakpoints.
- [x] Get tablet and desktop layouts
- [ ] Test across different browsers.
- [ ] Get peers to review.
- [ ] Submit for assessment.
